### ISSUE TITLE
Standalone js?

### ISSUE THREAD

**Issue by EndingCredits** [misode/deepslate#13]
Sorry if this is a bit of a nonsensical question, but I'm not very familiar with javascript and I don't really know how all the package management (well obviously that's node side, but how it gets translated to a final webpage) systems work.

Is it possible to get some sort of import-once-and-forget standalone js file (either local or remote)? The unpkg import works, but I can't work out how to do relative imports from it (i.e. get the individual sub-modules or whatever). 

Sorry again for such a basic question (I should probably just bite the bullet and learn how node works). I was having a look at rollling my own javascript schematic loader/viewer but this looks much more sophisticated! Do you have any particular plans for it?

**Comment by misode** [comment]
If you're working in the browser without a bundler, you should be able to us eth unpkg import. Instead of import statements everything is contained in the global variable `deepslate`, so for example

```js
const structure = new deepslate.Structure([4, 3, 4])
structure.addBlock([0, 0, 3], "minecraft:stone")
structure.addBlock([0, 1, 3], "minecraft:cactus", { "age": "1" })
```

Alternatively if you don't want to prefix everything with `deepslate`, you could use something like this:

```js
const { Structure, StructureRenderer } = deepslate
```

Also an important note is that you will need to import `gl-matrix` (for rendering) and `pako` (for reading nbt files) yourself if you're using one of those functions

**Comment by EndingCredits** [comment]
Thanks! Still not sure how much I understand javascripts module system, but this at least gives me a workable solution!

Though the next stumbling block is no simple way to load resources. There's obviously the Resource manager in the website code, but nothing in the core library. Is this deliberate (i.e. are we expected to use our own resources + resource management)?

**Comment by misode** [comment]
The reason this isn't included in the library is because it depends a lot on the environment (browser, node, vscode extension) and your uses. But maybe change my mind in the future.

For now you can copy the code from [this demo](https://github.com/misode/deepslate-demo/blob/main/main.js), though you may need to make some changes because that demo still uses v0.7.8, while the latest version is 0.9.0

**Comment by misode** [comment]
There is now a basic demo at https://github.com/misode/deepslate/tree/main/demo
The docs website with examples has been updated: https://misode.github.io/deepslate/
